// Entirely synthetic UI fixtures. These are not published government policies.
export const categories = ['전체', '생활·금융', '주거', '일자리', '교육', '건강·돌봄', '문화'];
export const regions = [
  '전국',
  '서울',
  '경기',
  '인천',
  '부산',
  '대구',
  '광주',
  '대전',
  '울산',
  '세종',
  '강원',
  '충북',
  '충남',
  '전북',
  '전남',
  '경북',
  '경남',
  '제주',
];

export const demoPolicies = [
  {
    id: 'demo-housing',
    title: '청년의 첫 독립, 주거비 지원',
    category: '주거',
    region: '서울',
    audience: '청년',
    organization: '주거지원 기관 예시',
    summary: '새로운 출발을 준비하는 청년의 주거 부담을 덜어주는 지원을 알아보세요.',
    benefit: '월세·주거비 지원 안내',
    tags: ['청년', '독립 준비'],
    icon: 'house',
    tone: 'sage',
    date: '2026-09-22',
  },
  {
    id: 'demo-employment',
    title: '다음 시작을 위한 취업 준비 지원',
    category: '일자리',
    region: '전국',
    audience: '청년',
    organization: '고용지원 기관 예시',
    summary: '진로 상담부터 직무 교육까지, 나에게 맞는 일을 찾는 과정을 함께해요.',
    benefit: '취업 상담·직무 교육 안내',
    tags: ['취업 준비', '역량 개발'],
    icon: 'briefcase',
    tone: 'blue',
    date: '2026-09-21',
  },
  {
    id: 'demo-learning',
    title: '배움의 기회를 넓히는 교육 지원',
    category: '교육',
    region: '전국',
    audience: '전체',
    organization: '교육지원 기관 예시',
    summary: '배우고 싶었던 분야가 있나요? 일상 속 배움을 이어갈 수 있는 기회를 찾아보세요.',
    benefit: '학습·교육비 지원 안내',
    tags: ['평생학습', '자기계발'],
    icon: 'book',
    tone: 'sand',
    date: '2026-09-20',
  },
  {
    id: 'demo-living',
    title: '든든한 일상을 위한 생활 지원',
    category: '생활·금융',
    region: '경기',
    audience: '가족',
    organization: '생활지원 기관 예시',
    summary: '가족의 안정적인 일상을 위해 필요한 생활 지원 정보를 한곳에서 살펴보세요.',
    benefit: '생활 안정 지원 안내',
    tags: ['가족', '생활 안정'],
    icon: 'wallet',
    tone: 'peach',
    date: '2026-09-19',
  },
  {
    id: 'demo-care',
    title: '가까이에서 함께하는 돌봄 서비스',
    category: '건강·돌봄',
    region: '전국',
    audience: '어르신',
    organization: '돌봄지원 기관 예시',
    summary: '도움이 필요한 일상에 따뜻한 손길을 더하는 지역 돌봄 서비스를 알아보세요.',
    benefit: '일상 돌봄·건강 상담 안내',
    tags: ['어르신', '돌봄'],
    icon: 'heart',
    tone: 'rose',
    date: '2026-09-18',
  },
  {
    id: 'demo-culture',
    title: '일상에 즐거움을 더하는 문화 지원',
    category: '문화',
    region: '부산',
    audience: '전체',
    organization: '문화지원 기관 예시',
    summary: '공연과 전시, 새로운 경험까지. 내 일상을 풍성하게 만드는 기회를 만나보세요.',
    benefit: '문화·여가 활동 안내',
    tags: ['문화생활', '여가'],
    icon: 'ticket',
    tone: 'lavender',
    date: '2026-09-17',
  },
];
