import {
  ArrowDownUp,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookOpen,
  Bookmark,
  Calculator,
  CalendarDays,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Compass,
  Heart,
  Headset,
  House,
  Info,
  Languages,
  LayoutGrid,
  MapPin,
  Menu,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Store,
  Ticket,
  UserRound,
  UsersRound,
  Wallet,
  X,
} from 'lucide-react';

const icons = {
  bell: Bell,
  arrow: ArrowRight,
  external: ArrowUpRight,
  book: BookOpen,
  bookmark: Bookmark,
  calculator: Calculator,
  calendar: CalendarDays,
  briefcase: BriefcaseBusiness,
  check: Check,
  down: ChevronDown,
  right: ChevronRight,
  help: CircleHelp,
  compass: Compass,
  heart: Heart,
  headset: Headset,
  house: House,
  info: Info,
  languages: Languages,
  grid: LayoutGrid,
  pin: MapPin,
  menu: Menu,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  filter: SlidersHorizontal,
  sparkles: Sparkles,
  sprout: Sprout,
  store: Store,
  ticket: Ticket,
  user: UserRound,
  users: UsersRound,
  wallet: Wallet,
  x: X,
  sort: ArrowDownUp,
};
export default function Icon({ name, size = 20, ...props }) {
  const Component = icons[name] || Compass;
  return (
    <Component size={size} strokeWidth={1.7} aria-hidden="true" focusable="false" {...props} />
  );
}
