import {
  ArrowDownUp,
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Bookmark,
  Calculator,
  CalendarDays,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Compass,
  Heart,
  Headset,
  House,
  Info,
  LayoutGrid,
  MapPin,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Ticket,
  UserRound,
  UsersRound,
  Wallet,
  X,
} from 'lucide-react';

const icons = {
  arrow: ArrowRight,
  external: ArrowUpRight,
  book: BookOpen,
  bookmark: Bookmark,
  calculator: Calculator,
  calendar: CalendarDays,
  briefcase: BriefcaseBusiness,
  check: Check,
  down: ChevronDown,
  right: ChevronRight,
  help: CircleHelp,
  compass: Compass,
  heart: Heart,
  headset: Headset,
  house: House,
  info: Info,
  grid: LayoutGrid,
  pin: MapPin,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  filter: SlidersHorizontal,
  sparkles: Sparkles,
  ticket: Ticket,
  user: UserRound,
  users: UsersRound,
  wallet: Wallet,
  x: X,
  sort: ArrowDownUp,
};
export default function Icon({ name, size = 20, ...props }) {
  const Component = icons[name] || Compass;
  return <Component size={size} strokeWidth={1.7} aria-hidden="true" {...props} />;
}
